### ISSUE TITLE
load model in colab - path not found 

### ISSUE THREAD

**Issue by rowntreerob** [facebookresearch/spiritlm#11]
examples/speech_generation/spirit_model.ipynb  is throwing an error loading the model. 

trying to install/ run in colab and looking like "lm-base-7b" not in local fs with path =
 '/usr/local/lib/python3.10/dist-packages/checkpoints/spiritlm_model/spirit-lm-base-7b' 
 
 I ran "setup.py install " and it looked to a nooby like its ok.
 however the path  '/usr/local/lib/python3.10/dist-packages/checkpoints  does not exist. 
 
 So I missed something for build/install/run on colab??
 
--stdout 
```
[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://localhost:8080/#) in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)
    464         raise EnvironmentError(f"There was a specific connection error when trying to load {path_or_repo_id}:\n{err}")
    465     except HFValidationError as e:
--> 466         raise EnvironmentError(
    467             f"Incorrect path_or_model_id: '{path_or_repo_id}'. Please provide either the path to a local folder or the repo_id of a model on the Hub."
    468         ) from e

OSError: Incorrect path_or_model_id: '/usr/local/lib/python3.10/dist-packages/checkpoints/spiritlm_model/spirit-lm-base-7b'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

**Comment by sraliu** [comment]
the checkpoints need download from https://ai.meta.com/resources/models-and-libraries/spirit-lm-downloads/ , However, there seems to be something wrong with this link, and the submission is not responding.

**Comment by rowntreerob** [comment]
will do as ref by #12
thank you

**Comment by hitchhicker** [comment]
Thanks @rowntreerob for raising the issue and thanks @tarekabouzeid for the PR!

@rowntreerob I wonder if you apply the fix in #12 does it work for you? Do you have a working open colab to share? Thanks!

**Comment by hitchhicker** [comment]
I just notice that this issue was closed automatically by Github, please reopen it if the issue is not resolved.

**Comment by rowntreerob** [comment]
im working on uploading the model to a working colab session
ttyl on my progress

thank you for helping out

**Comment by hitchhicker** [comment]
Please keep in mind that if your colab session is open to any third party, you should follow the guidance as per our [LICENSE](https://github.com/facebookresearch/spiritlm/blob/main/LICENSE), thanks!

**Comment by rowntreerob** [comment]
[image: image.png]

--resolved by:
1. use links to download the zip file for a single model
2. upload zip to g.drive
3. run the cell shown to unzip -
/content/drive/MyDrive/data/checkpoints/spiritlm_model/spirit-lm-base-7b"
4. use the path above to instantiate the model spirit_lm =
Spiritlm({path_to_model])
