### ISSUE TITLE
On the Details of Interleaving

### ISSUE THREAD

**Issue by acadarmeria** [facebookresearch/spiritlm#16]
Thank you for your great work and for making the model available! I have a question regarding the construction of interleaved text-HuBERT sequences: What is the frequency of modality switching (from text to speech and vice versa) when constructing the interleaved sequence? For example, every 5 or 10 words? Additionally, have you conducted any ablation studies to explore the impact of this configuration?

**Comment by hitchhicker** [comment]
Hey, thanks for your interests for our work! Please find the details in the appendix A.
> for the speech-text interleaving sampling strategy, we randomly select the word spans so that each text sequence contains 10-30 words and each speech sequence contains 5-15 words, we do this in order to balance the portion of speech tokens and text tokens in the input sequences.

We did ablate on the frequency, but that seems to have little impact on the current evaluation data.

**Comment by acadarmeria** [comment]
@hitchhicker Thanks for the reply! It solved my problem and I will close the issue.
