### ISSUE TITLE
mps plz

### ISSUE THREAD

**Issue by jumang4423** [facebookresearch/spiritlm#4]

**Comment by hitchhicker** [comment]
Could you explain more for your question? Thanks!

**Comment by hitchhicker** [comment]
Closing the issue since there is no description provided. Feel free to reopen it when more description is ready.

**Comment by lyonsno** [comment]
If I'm not misinterpreting that, I think it's a request for a version that can run with Metal Performance Shaders on M-series GPUs, which is something that I would be very interested in myself as well. I understand it might be a big lift, or flat-out impossible, but it would certainly be appreciated.

Either way, thanks for sharing your amazing work!
