### ISSUE TITLE
Datasets used for training?

### ISSUE THREAD

**Issue by eadwu** [facebookresearch/spiritlm#5]
The paper doesn't seem to actually list any of the open-source datasets used.

```
Speech-only datasets We employ open-sourced
large-scale speech datasets, totaling 460K hours of
speech or 30B speech tokens.
```

Later on there are sprinkles of mentions of datasets used in benchmarking that have train splits such as
- Expresso-Read (Expresso)
- EMOV

(Responsible Evaluation)
- HOLISTICBIAS

Looking to augment my stash with more datasets which is why I'm interested.

**Comment by hitchhicker** [comment]
Good question! Unfortunately, we can not share the details of the training set.
