### ISSUE TITLE
Mistake (I think) in adding speech token in prompt building

### ISSUE THREAD

**Issue by gallilmaimon** [facebookresearch/spiritlm#8]
- When building the prompt in the model you add the speech token, if the prev_modality != 'a'
https://github.com/facebookresearch/spiritlm/blob/9756989115db5b5e33d0c9a26f01c5e8d093a274/spiritlm/model/spiritlm_model.py#L194

- However, as far as I can understand the prev_modality is never 'a' but rater [None, 't', 's'], I think this is supposed to be  prev_modality != 's' indicating a move to the speech modality (either from text or at the start).

I would appreciate a clarification or a fix if one is needed. Thanks!

**Comment by gallilmaimon** [comment]
In practice, if the prompt is truly interleaved (text-speech-text) this shouldn't be a problem but if the prompt has audio followed by another audio segment this will create an extra speech token which shouldn't be there.

**Comment by hitchhicker** [comment]
Good catch! You are right, it should be
```
if prev_modality != "s":
```

I just pushed the [fix](https://github.com/facebookresearch/spiritlm/commit/3e74a0231b00af64ba8caa4c4e6964ee2e4a506c).

Thanks for pointing out!
